name: cppcheck

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: docker login
      uses: docker/login-action@v1
      env:
        GITHUB_USER: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        registry: ghcr.io
        username: $GITHUB_USER
        password: ${{ secrets.PAT }}

    - run: docker pull ghcr.io/patrickdowling/cdpfw-avr:latest

    - name: check cdp_control
      run: |
        docker run --rm -v ${{ github.workspace }}:/build ghcr.io/patrickdowling/cdpfw-avr:latest make -C cdp_control check CPPCHECK_EXTRA="-q --error-exitcode=1"

    - name: check amp_control
      run: |
        docker run --rm -v ${{ github.workspace }}:/build ghcr.io/patrickdowling/cdpfw-avr:latest make -C amp_control check CPPCHECK_EXTRA="-q --error-exitcode=1"

